### ISSUE TITLE
Deploy to jsdelivr

### ISSUE THREAD

**Issue by homer2** [BenjaminVanRyseghem/numbro#105]
Have you considered submitting the project to http://www.jsdelivr.com? I have found it useful for quickly bundling CDN files for my prototypes. I found numeraljs there but not numbro.

**Comment by BenjaminVanRyseghem** [comment]
I did not as I was not aware of this service :smile:

But it feels like a good idea :wink:
Do you want to do it? :smile:

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage

**Comment by BenjaminVanRyseghem** [comment]
then no need to do anything, or?

**Comment by jimaek** [comment]
Not really 
http://cdn.jsdelivr.net/npm/numbro@1
http://cdn.jsdelivr.net/npm/numbro/

**Comment by BenjaminVanRyseghem** [comment]
I close this issue as:
- there is nothing to do :)
- the CDN link points to jsdeliver

thanks :smile:
