### ISSUE TITLE
Uppercase 0.0a format

### ISSUE THREAD

**Issue by Tiagojdferreira** [BenjaminVanRyseghem/numbro#115]
Is there a way to make uppercase the default for all letters used in format(0.0a), example:
Instead of 12m have 12M

**Comment by BenjaminVanRyseghem** [comment]
why?

there are multiple ways to do it (even though it feels wrong):

- override all languages defaults
- use CSS text-transformation

**Comment by Tiagojdferreira** [comment]
Because it is one of the requirements of the project I am currently working on. Considering there are several places where numbers are show, they do not necessarily have similar css classes the CSS solution does not seem viable.
Overriding all the defaults also seems kind of ugly, but I think I will end up doing just that for now. 

However, it would be cool if there was a way to pass a function that did some default post-processing, something in the likes of:
````
numbro.postProcessing(String.prototype.toUpperCase);
````
And this would do to all outputs:
````
String.prototype.toUpperCase.call(output)
````

**Comment by BenjaminVanRyseghem** [comment]
why don't you do it like:

```javascript
var myFormat = function(value, format, postFn) {
    var output = numbro(value).format(format);
    return postFn(output);
}
```

**Comment by agquick** [comment]
FWIW, I also have this requirement (uppercase rather than lower). Would be cool if I could specify the format as '0A' rather than '0a' to denote uppercase.

**Comment by BenjaminVanRyseghem** [comment]
still don't get why you don't just wrap it to uppercase it afterward
