### ISSUE TITLE
CDN link on language page is broken, version is missing

### ISSUE THREAD

**Issue by timaschew** [BenjaminVanRyseghem/numbro#158]
This is the output:

``` html
<script src="//cdnjs.cloudflare.com/ajax/libs/numbro//min/languages.min.js"></script>
```

Here is the source code for it: https://github.com/foretagsplatsen/numbro/commit/6487f3a73826d3ababaa412fbd5da8b1143901c6#diff-1c9501c42c99607777a290d798f3b4e0R19

**Comment by sergioaugrod** [comment]
👍

**Comment by BenjaminVanRyseghem** [comment]
done, thanks
