### ISSUE TITLE
Why I can't set percent format with percent sign at the beginning?

### ISSUE THREAD

**Issue by walerun** [BenjaminVanRyseghem/numbro#307]
```javascript
numbro(0.1).format("0.00%")
// "10.00%"

numbro(0.1).format("%0.00")
// "10.00%"
```

**Comment by BenjaminVanRyseghem** [comment]
I think it's because it was not thought to be a use case.

Could you describe in which context you need the percent sign to be a prefix?

Thanks in advance

**Comment by walerun** [comment]
Thanks for the answer.
Well, it would be consistency as we do it with currency sign. I see that MS Excel do it well. But I agree it's rare use case.

**Comment by BenjaminVanRyseghem** [comment]
It can be easily added (at least in 2.0)

I'll add it to the todo list :smile:

**Comment by BenjaminVanRyseghem** [comment]
Done in #305
