### ISSUE TITLE
formatCurrency with a string format throws

### ISSUE THREAD

**Issue by ahmedelgabri** [BenjaminVanRyseghem/numbro#321]
```js
numbro('23555.12').formatCurrency('0,0.00')
```

result in

```
Uncaught TypeError: Cannot create property 'output' on string '0,0.00'
```

Fails on this line, looks like `format` here is a string & trying to set `output` on that string
https://github.com/BenjaminVanRyseghem/numbro/blob/be6a8c33197b83ed9a3b30120bb535328c7897bc/src/numbro.js#L42-L44

**Comment by BenjaminVanRyseghem** [comment]
thanks for the feedback

**Comment by BenjaminVanRyseghem** [comment]
thanks for the feedback
