### ISSUE TITLE
Unable to resolve module `./globalState`

### ISSUE THREAD

**Issue by achmadk** [BenjaminVanRyseghem/numbro#325]
I am using numbro inside my react native app project. Unfortunately I got this error.

```bash
Error: Unable to resolve module `./globalState` from `${project_directory}\node_modules\numbro\dist\numbro.js`: The module `./globalState` could not be found from `${project_directory}\node_modules\numbro\dist\numbro.js`. Indeed, none of these files exist:

  * `${project_directory}\node_modules\numbro\dist\globalState(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
  * `${project_directory}\node_modules\numbro\dist\globalState\index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
```

It seems that `globalState` folder is not exist inside `dist` folder.

**Comment by BenjaminVanRyseghem** [comment]
how are you requiring numbro?
how are you bundling your app?

Everything should be minified in numbro, thus `globalState` should be included.

There are few tests [here](https://github.com/BenjaminVanRyseghem/numbro/tree/develop/integrationTests) to cover integration.

**Comment by achmadk** [comment]
```js
import numbro from 'numbro'

let costString = `IDR ${numbro(300000).format('0,0')}`
```

I try to replace `import numbro from 'numbro'` to `import {numbro} from 'numbro'` and `let numbro = require('numbro')` still get same error.

**Comment by orangesoup** [comment]
@achmadk Try `import * as numbro from 'numbro'`, it works (at least in Angular).

**Comment by achmadk** [comment]
Unfortunately the result is still not working @orangesoup . I delete `node_modules` folder then re-add again with run `npm i` still not working too.

**Comment by BenjaminVanRyseghem** [comment]
how are you bundling your app?

**Comment by achmadk** [comment]
Because my project is react native app, the bundling process is processed by react native itself.

**Comment by achmadk** [comment]
https://github.com/BenjaminVanRyseghem/numbro/blob/fb853def65cdf4ed1ec523e45abaa368b20ecb93/dist/numbro.js#L2838

I have checked this libraries entry file and I have found that there is no folder or file called `globalState` inside `dist` folder. Maybe this will get more error that folder or file called `validating` and `parsing` is not exist.

Maybe you should use rollup to bundle numbro's module.

**Comment by BenjaminVanRyseghem** [comment]
The problem come from the fact that npm doesn't serve the minified version of numbro.

I just fixed it, and as soon as travis validate the build, I'll release a new version

**Comment by BenjaminVanRyseghem** [comment]
is it ok now?

**Comment by achmadk** [comment]
Yes, Mr. @BenjaminVanRyseghem . You can close this issue.
