### ISSUE TITLE
unformat not working with non localized delimiters

### ISSUE THREAD

**Issue by jkettmann** [BenjaminVanRyseghem/numbro#328]
We are using different languages like `en-US` and `de-DE` where delimiters are different according to the language.

When `de-DE` is selected (thousand delimiter is `.`, decimal is `,`) and we call

```
numbro.unformat('180.000')
```

the result is `180` opposed to the expected `180000`. The reason is [this line](https://github.com/BenjaminVanRyseghem/numbro/blob/develop/src/unformatting.js#L194), which is not respecting the delimiters.

```
if (!isNaN(+inputString)) {
        return +inputString;
}
```

I guess this was added for performance reasons!? When I remove it, everything is working as expected.

**Comment by BenjaminVanRyseghem** [comment]
thanks, I'll have a look :smile:

**Comment by andi-dev** [comment]
I just ran into exactly the same issue. @BenjaminVanRyseghem, do you plan to merge and release this PR? This is currently blocking my transition from numeral.js to numbro.js, which is otherwise done and working well. If I can help with anything please let me know.

**Comment by andi-dev** [comment]
Thank you Benjamin, looking forward to update and remove my workaround once this makes it in a release!

**Comment by Rambobafet** [comment]
Hi Benjamin, do you have an idea about the release date of this fix? :)

**Comment by BenjaminVanRyseghem** [comment]
in numbro 2.1.2

Sorry guys for the delay, tough times here 😕

**Comment by Rambobafet** [comment]
Thanks Benjamin, wish you the best
