### ISSUE TITLE
Is there a way to register all the languages at once? #v2

### ISSUE THREAD

**Issue by NouranMahmoud** [BenjaminVanRyseghem/numbro#335]
I wanted to register all languages to switch between them dynamically. The documentation is not clear enough regarding this.

This is my code 
```
  // numbro
  var numbro = require("numbro");
  var languages = require('numbro/dist/languages.min.js');

numbro.registerLanguage(languages['cs-CZ']);
numbro.setLanguage('cs-CZ');
formatedNum = numbro(num).formatCurrency(format);
```

In numeraljs, I can do the followings:-

```
const numeral = require('numeral');
require('numeral/locales');

numeral.locale('de');
formatedNum = numeral(num).format(format);
```
So, In numeraljs I don't need to register each language first to be able to use it. Is there a way for numbrojs?

**Comment by BenjaminVanRyseghem** [comment]
there is `dist/languages.min.js` which should be what you are looking for 😄

**Comment by NouranMahmoud** [comment]
I did load it using `require('numbro/dist/languages.min.js')` but this line doesn't register all the languages to the languages object.

I imported the numbrojs like that
```
var numbro = require("numbro");
require('numbro/dist/languages.min.js');
```
Check this screenshot
https://imgur.com/Xd3qiiw

**Comment by BenjaminVanRyseghem** [comment]
```js
let numbro = require("numbro");
let numbroLanguages = require("numbro/dist/languages.min.js");
Object.values(numbroLanguages).forEach((each) => numbro.registerLanguage(each));

numbro.languages();  // => lot of languages
```

**Comment by diogofcunha** [comment]
@BenjaminVanRyseghem would you accept a pr to a side effective require for the languages? that solution looks kind of hacky

**Comment by BenjaminVanRyseghem** [comment]
@diogofcunha we (the community and I) had this discussion in the past, and we concluded that most of the time, we don't want to integrate all languages, but just a subset. And to optimize the size of the library, we went for not including automatically a language.

Now, if someone has the time and the willingness to build a "numvbro kitchen" where one choose languages he/she want and that then bundle them, that would be awesome :smile:

**Comment by diogofcunha** [comment]
@BenjaminVanRyseghem can see the point there.

On your second point, do you mean something that could run on the first npm install, create a json config file register languages on demand using that?

Wouldn't it be easier to just include what you need or everything and allow side effects in those imports? Something like what's used by rxjs to make the bundle smaller. You can either import everything or require the operators you wish (https://www.learnrxjs.io/concepts/operator-imports.html)

**Comment by BenjaminVanRyseghem** [comment]
@diogofcunha I was thinking about an online kitchen à la [jQuery-ui](https://jqueryui.com/download/)

**Comment by diogofcunha** [comment]
@BenjaminVanRyseghem that would work really well for script tags.

As long as my knowledge goes, wouldn't that be blocking the nodeJS folks from using it?

npm will probably represent 90% of this library usage in the next couple of years, and in my personal experience pure npm dependencies are much easier to manage then script tags

**Comment by BenjaminVanRyseghem** [comment]
> As long as my knowledge goes, wouldn't that be blocking the nodeJS folks from using it?

most probably

> npm will probably represent 90% of this library usage in the next couple of years, and in my personal experience pure npm dependencies are much easier to manage then script tags

I agree with you, but since size matters less in npm (as you usually rue a compiler that will trim unused code) all languages are shipped. In numbro 1, there was a function to load all languages in a node env, but it brought a lot of issues (detecting the env).

Now we could give it another try :smile:

**Comment by diogofcunha** [comment]
Sorry I may not have explained myself very well.

The separation between languages and numbro core it's an amazing idea, I'm not proposing that you should add it in for node.

What I mean it's that for node users this should be a little bit easier to do. and that you could still import separate or merged chuncks of languages.

I have a few ideas, will try to find time over the next few days to open a PR with all the topics of this conversation in mind.

**Comment by BenjaminVanRyseghem** [comment]
Thanks in advance :smile:
