### ISSUE TITLE
Mantissa not taken into account when no decimals

### ISSUE THREAD

**Issue by BenjaminVanRyseghem** [BenjaminVanRyseghem/numbro#343]
```js
numbro(1000).format({ mantissa: 2}) //> 1000
```

where it should be `1000.00`

**Comment by misaki-naki** [comment]
@BenjaminVanRyseghem, I recently used numbro 2.3.2 and for integers the mantissa is still ignored, the expression `numbro(1).format({ mantissa: 2 })` will return `1`, not `1.00`
