### ISSUE TITLE
Old format (question)

### ISSUE THREAD

**Issue by SergeyShablenko** [BenjaminVanRyseghem/numbro#354]
Does old format deprecated, or it will be kept?
It is very useful and simple to use old formats, I think it would be nice if you`ll keep it and support it

**Comment by GammaGames** [comment]
I'm looking to see if this would work as an alternative to numeral. We use the format function a lot, and there's not a reason to switch away from numeral if the old format were to be dropped from numbro. @BenjaminVanRyseghem Do you have any plans on the subject?

**Comment by BenjaminVanRyseghem** [comment]
Sorry, I thought I answered that question.

The old format will be supported as much as possible, but the format is quite messy, and quite limited in what can be easily expressed (that's why we introduced the new format)
