### ISSUE TITLE
Maximal mantissa

### ISSUE THREAD

**Issue by leahaense** [BenjaminVanRyseghem/numbro#358]
I would like to format my numbers with a mantissa of at most 4, so if there are less decimals, it will not fill up with zeros. E.g. 1.23 => 1.23, 1.234 => 1.234, 1.2345 => 1.2345, 1.23456 => 1.2346. With the old format this could be done with this format string `0,0[.][0000]`. How can this be achieved with the new formatting?
Btw. I just noticed that also when using the old format string with the latest version, the behaviour is not as expected, it always fills up with zeros at the end.

**Comment by BenjaminVanRyseghem** [comment]
You currently can't.

But I just added a new parameter `trimMantissa` which will allow you to experience the same behaviour.

It will be available with the next release.

**Comment by leahaense** [comment]
Thanks for your fast answer. Any idea when this will be released?

**Comment by BenjaminVanRyseghem** [comment]
in numbro 2.1.0

**Comment by BenjaminVanRyseghem** [comment]
> Thanks for your fast answer. Any idea when this will be released?

now 😄
