### ISSUE TITLE
Bytes translation

### ISSUE THREAD

**Issue by jlesceau** [BenjaminVanRyseghem/numbro#359]
I think it would be interesting to have an entry in the translation definition to specify the "byte" symbol in other languages than en-US. For example in french it would be "o" for "octet".
I believe that a lot of french people are not even familiar with Mo/Go and what it represents, so i'd prefer not to use MB/GB. Maybe they are less silly than I might think :)

**Comment by BenjaminVanRyseghem** [comment]
in numbro 2.3.0
