### ISSUE TITLE
Format Decimal without Rounding

### ISSUE THREAD

**Issue by shefrancia** [BenjaminVanRyseghem/numbro#364]
Hi,

Is there way to format decimal without rounding up?
e.g. format = {mantissa: 2}
current behavior: 1.879 -> 1.88
desired behavior: 1.879 -> 1.87

Many thanks!

**Comment by edwardfhsiao** [comment]
This feature really matters in most buying selling scenarios.
It can be very helpful if you integrate into the library.

**Comment by BenjaminVanRyseghem** [comment]
in numbro 2.2.0

**Comment by edwardfhsiao** [comment]
@BenjaminVanRyseghem 
Hi, is this a typo in your documentation?
![image](https://user-images.githubusercontent.com/11728228/77025378-e3d6bc80-69cb-11ea-9861-b1f797f33ae8.png)

**Comment by edwardfhsiao** [comment]
@BenjaminVanRyseghem  Thanks.

```js
options = {
    mantissa: 2,
    trimMantissa: true
};
options.roundingFunction = Math.floor;
expect(numbro(1.236).format(options)).toBe("1.23");
```
