### ISSUE TITLE
mantissa: 0 and trimMantissa: true results in truncated numbers

### ISSUE THREAD

**Issue by timfish** [BenjaminVanRyseghem/numbro#372]
![image](https://user-images.githubusercontent.com/1150298/44426387-cabb1f00-a58e-11e8-9c94-d288da2234ed.png)

https://runkit.com/timfish/5b7c70e7466e950012e31356

**Comment by cnrudd** [comment]
Hi,  
We would like to switch from numeral.js to numbro.js, but this issue is blocking us.  
Thank you!
Colin

**Comment by cnrudd** [comment]
Thank you very much for merging this in!
-Colin
