### ISSUE TITLE
Localised foreign currency

### ISSUE THREAD

**Issue by fwal** [BenjaminVanRyseghem/numbro#382]
Hello!

Trying to figure out how to handle foreign currencies together with the users locale.
For example in the US you write `$100` for a hundred dollars but if you're displaying a foreign currency you often display the currency code instead, like this for one hundred Swedish krona for  en-US locale: `SEK 100`.

And for a Swedish user it should be the opposite: `100 USD` and `100 kr` (notice the currency symbol is after the amount).

While I can see that currency code is defined for the different languages I can't figure out how to use them and how to set the currency for formatting, am I missing something? 😅

**Comment by BenjaminVanRyseghem** [comment]
Hej

I'll do something like

```js
let { symbol } = numbro.languages()["sv-SE"].currency;
numbro(100).formatCurrency({currencySymbol: symbol}); //=> "kr100"
```

**Comment by fwal** [comment]
Nice! Ended up writing something similar in a helper where `code` is the currency code for the amount I'd like to display...
```js
const currencySymbol = code => {
  const { currency } = numbro.languageData()
  return code === currency.code ? currency.symbol : code
}
```

Thanks for the help! 🙂
