### ISSUE TITLE
BigNumber Issue - new BigNumber() number type has more than 15 significant digits

### ISSUE THREAD

**Issue by j0nxs** [BenjaminVanRyseghem/numbro#383]
Hello, 

thx for this great library, but i have one thing which is very importent for me. 
Please support bigger numbers or a configurable option to set the BigNumber Object to no error reporting.
In the following link can you see my problem. I have no option to change your BigNumber Object from external.

https://github.com/MikeMcl/bignumber.js/issues/14

**Comment by shablenko-sednor** [comment]
Any news here? Issue still there, how to prevent crash?

**Comment by BenjaminVanRyseghem** [comment]
@all-contributors please add j0nxs for bug

**Comment by BenjaminVanRyseghem** [comment]
in numbro 2.3.0
