### ISSUE TITLE
Small negative numbers get the leading zero incorrectly cut off 

### ISSUE THREAD

**Issue by cnrudd** [BenjaminVanRyseghem/numbro#392]
Small negative numbers get the leading zero incorrectly cut off when rounded and thousandSeparated.

See demo of bug:
https://numbrojs.com/try-me.html?lang=en-US&value=-0.00490&format=%7B%22mantissa%22%3A2%2C%22trimMantissa%22%3Afalse%2C%22thousandSeparated%22%3Atrue%7D

**Comment by BenjaminVanRyseghem** [comment]
in numbro 2.2.0

**Comment by cnrudd** [comment]
Merci!
