### ISSUE TITLE
spaceSeparated is not working - version 2.0.5

### ISSUE THREAD

**Issue by RichColours** [BenjaminVanRyseghem/numbro#411]
Same symptoms as on your main webpage:

https://numbrojs.com/format.html#bytes

the spaceSeparated is not doing anything.

![image](https://user-images.githubusercontent.com/13033494/53969371-95bc8700-40f0-11e9-88a2-015a48c38677.png)

In my particular issue:

const size = numbro(x.sizeBytes).format({
                                                        spaceSeparated: true,
                                                        output: "byte",
                                                        base: "decimal",
                                                        mantissa: 1
                                                    });

            return `<tr><td>${x.filename}</td><td>${x.dateModifiedHuman}</td><td>${size}</td><td>${x.md5sum}</td></tr>`;

(apologies, GitHub's 'code' delimiter is Javascript's third type of string literal with escaping operator.

My output string is:

![image](https://user-images.githubusercontent.com/13033494/53969427-b1c02880-40f0-11e9-9d60-53dd8085216d.png)

**Comment by RichColours** [comment]
It is working on percentages though.

**Comment by kruthoff** [comment]
I have the same issue on the latest version, currently 2.3.0. Any chance to get this fixed?

**Comment by BenjaminVanRyseghem** [comment]
in 2.3.1

**Comment by BenjaminVanRyseghem** [comment]
@all-contributors please add @RichColours  for bug
