### ISSUE TITLE
Invalid thousand separator for de-CH

### ISSUE THREAD

**Issue by FrEaKmAn** [BenjaminVanRyseghem/numbro#414]
Based on http://www.localeplanet.com/icu/de-CH/index.html and http://cldr.unicode.org/, thousand separator for de-CH must be

`’` (\u2019)

instead of 

`'` (\u0027)

**Comment by BenjaminVanRyseghem** [comment]
thanks!

**Comment by FrEaKmAn** [comment]
@BenjaminVanRyseghem thanks for quick reply, I can provide PR if you have time for merge?

**Comment by BenjaminVanRyseghem** [comment]
that would be awesome :smile:

**Comment by BenjaminVanRyseghem** [comment]
in numbro 2.2.0
