### ISSUE TITLE
formatCurrency - forceSign doesn't work properly when number is positive

### ISSUE THREAD

**Issue by adriang133** [BenjaminVanRyseghem/numbro#418]
```
numbro(1000).formatCurrency({forceSign: true}) -> $+1000
numbro(-1000).formatCurrency({forceSign: true}) -> -$1000
```
I would expect the first one to be +$1000

**Comment by Kramy** [comment]
Same problem here. Tested with _en-Gb_ and _en-AM_ locales.

**Comment by firebotQL** [comment]
Hi, I am currently having this issue as well. I've noticed there is a PR hanging since April for this issue by @adriang133 . Any idea when it will be merged and released @BenjaminVanRyseghem? Thanks

**Comment by BenjaminVanRyseghem** [comment]
Sorry, I am a bit off those days. Between a new job and a newborn, I am a bit running after free time :smile:

**Comment by BenjaminVanRyseghem** [comment]
in numbro 2.2.0
