### ISSUE TITLE
2.1.0 not in CDN

### ISSUE THREAD

**Issue by Deele** [BenjaminVanRyseghem/numbro#419]
You have CDN URLs for latest version in page like `//cdnjs.cloudflare.com/ajax/libs/numbro/2.1.0/numbro.min.js`, but it returns 404 error.

If you do a search in https://cdnjs.com/ you will find that there is only 2.0.5

![image](https://user-images.githubusercontent.com/477326/55944042-6ac5d580-5c50-11e9-807e-ce9dda223c12.png)

**Comment by pranithan-kang** [comment]
Please see #446

**Comment by BenjaminVanRyseghem** [comment]
done, thanks for reporting!
