### ISSUE TITLE
totalLength negative numbers

### ISSUE THREAD

**Issue by jlismore** [BenjaminVanRyseghem/numbro#425]
This might be a documentation issue rather than a functionality issue.
Per the [format documemtation](https://numbrojs.com/format.html) the totalLength option specifies the precision, but it actually seems to limit the final length of the formatted value. 
I want to produces numbers formatted to 3sf and per the format docs this seems the right option
```
numbro(1011).format({totalLength: 3}) // 1.01k
numbro(-1011).format({totalLength: 3}) // -1.0k, expecting -1.01k
```

**Comment by DamienCassou** [comment]
This is a change of behavior between numbro 1.11.1 (on the left) and numbro 2.2.0 (on the right):

![2020-05-07-153820](https://user-images.githubusercontent.com/217543/81301111-eb841a80-9078-11ea-94b9-1c002ff61b02.png)

**Comment by DamienCassou** [comment]
The PR #537 fixes this issue:

```
> numbro(-1011).format({totalLength: 3})
'-1.01k'
```

**Comment by BenjaminVanRyseghem** [comment]
in numbro 2.3.0
