### ISSUE TITLE
CDN is broken

### ISSUE THREAD

**Issue by BryanBarrera** [BenjaminVanRyseghem/numbro#438]
I was looking through the documentation and wanted to play around with the latest release (2.1.1) but on the homepage the CDN showing is (2.1.0), when using (2.1.) (https://cdnjs.cloudflare.com/ajax/libs/numbro/2.1.0/numbro.min.js) it appears it is broken. 

Can someone fix this?

**Comment by pranithan-kang** [comment]
Please see #446

**Comment by BenjaminVanRyseghem** [comment]
done, thanks for reporting!
