### ISSUE TITLE
CDNJS in website Relocation

### ISSUE THREAD

**Issue by pranithan-kang** [BenjaminVanRyseghem/numbro#446]
Hi,
According to #356, Please Change the CDNJS URL inside the [web](http://numbrojs.com/getting-started.html#download) from `<script src="//cdnjs.cloudflare.com/ajax/libs/numbro/x.x.x/numbro.min.js"></script>` to `<script src="https://cdn.jsdelivr.net/npm/numbro@x.x.x/dist/numbro.min.js"></script>`

**Comment by BenjaminVanRyseghem** [comment]
done, thanks!

**Comment by BenjaminVanRyseghem** [comment]
in numbro 2.2.0
