### ISSUE TITLE
How to apply across multiple elements?

### ISSUE THREAD

**Issue by rognales** [BenjaminVanRyseghem/numbro#449]
Hi

How do i initialize the library and apply the formatting across all elements that match an CSS selector?

**Comment by BenjaminVanRyseghem** [comment]
could you please provide some more context?

**Comment by rognales** [comment]
My usecase is to apply this via CSS class

document.getElementsByClassName('.money');

and apply the same formatting to all elements

**Comment by BenjaminVanRyseghem** [comment]
Something like this maybe

```js
document.getElementsByClassName('.money').forEach((node) => node.innerText = numbro(node.innerText).format({YOUR_OPTIONS});
```

?

**Comment by rognales** [comment]
Ooo, as simple as that.
