### ISSUE TITLE
numbro.unformat(percentage_str) gives incorrect values

### ISSUE THREAD

**Issue by manoojm** [BenjaminVanRyseghem/numbro#459]
Hi,

I know this is an underlying javascript issue but I saw in the release notes that numbro has now moved on to use the bignumber.js. So, the result seems kind of strange to me. 

numbro.unformat('0.45799%') ---> //0.0045799000000000005  (incorrect value)
whereas if we do,
let bigNum = new bigNumber(0.45799);
bigNum.dividedBy(100).toNumber(); ---> //0.0045799  (correct value)

Please advice on how we should use to get the right value.

Manooj

**Comment by manoojm** [comment]
ok.. I found a solution to this, so posting it here for confirmation,

if(number.endsWith('%')) {
        parsedNumber = numbro(number.replace('%', '')).divide(100).value();
 }

**Comment by Ray-56** [comment]
Thanks
