### ISSUE TITLE
numbro.unformat ignore byte style inputs

### ISSUE THREAD

**Issue by manoojm** [BenjaminVanRyseghem/numbro#461]
We are using numbro to format/unformat inputs. Currently unformat returns 2 for an input B2, because it checks if the inputs is in the for form of byte style. We would want a way to bypass this behavior i.e. for such input patterns, unformat should return 'undefined'. Please let us know how can this be achieved?

**Comment by manoojm** [comment]
Any suggestions please?

**Comment by BenjaminVanRyseghem** [comment]
you could maybe use the `+` operator to try to parse it?

**Comment by manoojm** [comment]
Can u please provide an example? Are you suggesting the javascript +? We want to use unformat as it handles cases like %, currencies etc. we only want to bypass this rule

**Comment by manoojm** [comment]
we are running into this very often in our tests. An example would help me close this soon. Please help.

**Comment by manoojm** [comment]
Ping....

**Comment by manoojm** [comment]
Benjamin, It is really important for us to fix this ASAP. Any assistance would be helpful.

**Comment by manoojm** [comment]
Well,, I guess there is no point reaching out for help here. Will try exploring other library replacements.

**Comment by BenjaminVanRyseghem** [comment]
Farewell then.

You should really read what MIT means, especially in terms of support.

**Comment by manoojm** [comment]
Wow.. of all the messages I left on the subject you choose to respond to this...

**Comment by BenjaminVanRyseghem** [comment]
because I had nothing to answer to your previous messages, either because having no time for it, or because I had no clue. Yet you keep on pushing, ultimately threatening to move to another library.

Sorry to say, but my time is limited like for anybody else. Also, MIT means no support is guaranteed. If you build your company tech stack over MIT projects, then you should understand that most solutions are up to you to find.

**Comment by manoojm** [comment]
I wasn't pushing anything... U responded to this thread the first time which gave me the impression that u would be interested in helping me solve the problem... That is the reason I tried providing more info on the usecase.. I left multiple messages assuming atleast one of them would catch ur attention amidst your busy schedule.... There is nothing threatening here about looking at other libraries.. it only means that I would look at how others are handling such inputs and perhaps might help me in implementing a solution on my own (or) I rather find a library which does solve my problem and I start using it.. MIT goes both ways..  

Requesting for help should not be misunderstood as demand for support... Hope things are clear now..
