### ISSUE TITLE
Negative number is not handled correctly .

### ISSUE THREAD

**Issue by bhartidengada** [BenjaminVanRyseghem/numbro#462]
For example:-
numbro( 
-1.2
 ).format({ 
mantissa : 5, characteristic: 3
 });
output :-  0-1.20000
but correct out should be -001.20000

**Comment by bhartidengada** [comment]
any suggestion for this issue.

**Comment by BenjaminVanRyseghem** [comment]
It's  definitely a bug.

I will try to address it asap, but if  you have any suggestion to fix it, PRs are welcomed :smile:

**Comment by bhartidengada** [comment]
Hello,

Thanks you for response.
Yes I have fix for this issue, I will create PR.
Just small question I have on which branch I should create PR.

Thanks & Regards,
Bharti

________________________________

**Comment by BenjaminVanRyseghem** [comment]
`develop` :smile:

**Comment by BenjaminVanRyseghem** [comment]
in numbro 2.3.0
