### ISSUE TITLE
Format the value as 'HH:mm' and ignore the seconds part

### ISSUE THREAD

**Issue by benjaminliugang** [BenjaminVanRyseghem/numbro#464]
How to format the value as 'HH:mm'? I tried with below format:

1. numbro(600).format('00:00') = "0:10:00"
2. numbro(600).format('HH:mm') = "0:10:00"

The value is not expected by us, we expected to get "10:00".

**Comment by BenjaminVanRyseghem** [comment]
I would advise you to use [moment](momentjs.com/) for a real time formatting solution.

`numbro` offers very few options when it comes to time formatting, no willing to reinvent the wheel

**Comment by benjaminliugang** [comment]
Ok, Thanks!
