### ISSUE TITLE
trimMantissa vs optionalMantissa

### ISSUE THREAD

**Issue by cornflakeboy** [BenjaminVanRyseghem/numbro#469]
Hey,
could you tell me what's the difference between trimMantissa and optionalMantissa. They both seem do drop unnecessary zeros...

best, Tim

**Comment by BenjaminVanRyseghem** [comment]
IIRC, `optionalMantissa` will remove the mantissa if it equals zero:

`12.00` -> `12`
`12.10` -> `12.10`
http://numbrojs.com/try-me.html?lang=en-US&value=12.10&format=%7B%22mantissa%22%3A2%2C%22optionalMantissa%22%3Atrue%7D

while `trimMantissa` will trim it:
`12.00` -> `12`
`12.10` ->  `12.1`
http://numbrojs.com/try-me.html?lang=en-US&value=12.10&format=%7B%22trimMantissa%22%3Atrue%7D

**Comment by cornflakeboy** [comment]
Oh, thanks. That makes sense :)
