### ISSUE TITLE
Can't find how to load languages in TS

### ISSUE THREAD

**Issue by Varkal** [BenjaminVanRyseghem/numbro#534]
Hello,

I'm trying to use the localization part of numbro in a front-end application written in typescript.

- `import "numbro/dist/languages.min.js";`doesn't seem to be enough to loading the languages.
- `numbro/dist/languages`, `numbro/dist/languages.min`, `numbro/languages` all fails to import

- There is no definition file for the language file, so, I can't use language file content in typescript:  any import `import * as languages from "numbro/dist/languages.min.js";` throw a compiler error
```
Could not find a declaration file for module 'numbro/dist/languages.min.js'. .../node_modules/numbro/dist/languages.min.js' implicitly has an 'any' type.
  Try `npm install @types/numbro` if it exists or add a new declaration (.d.ts) file containing `declare module 'numbro/dist/languages.min.js';`ts(7016)
```
So, how can i load the languages in typescript

**Comment by BenjaminVanRyseghem** [comment]
Hi!

I'm sorry, I've never used typescript, so I can't help 😕 

Hopefully someone in the community will help you

**Comment by ridesz** [comment]
Hi @Varkal !

I hope I can show you a workaround for the problem:

https://codesandbox.io/s/numbro-locale-settings-jv5hn

I use this helper function to load a given language for `numbro` in TypeScript:

```typescript
function setNumbroLocale(locale: string): void {
  try {
    if (!numbro.languages()[locale]) {
      // Unfortunatelly we need to include the languages file directly.
      // eslint-disable-next-line @typescript-eslint/no-var-requires
      const languages = require("numbro/dist/languages.min.js");
      if (languages) {
        const numbroLanguage = languages[locale];
        if (numbroLanguage) {
          numbro.registerLanguage(numbroLanguage);
        }
      }
    }
    numbro.setLanguage(locale);
  } catch (error) {
    console.log(
      "Error with configuring numbro" +
        (error.message ? ": " + error.message : ".")
    );
    console.log(error);
  }
}
```

Example:

```typescript
setNumbroLocale("en-GB");
```

Unfortunately this works for me only with the `2.1.0` version of `numbro`. (The import doesn't work with the later versions and I think that this problem is related to this issue: https://github.com/BenjaminVanRyseghem/numbro/issues/403 )

**Comment by Varkal** [comment]
@ridesz Thanks for your help ! 

As I need only one locale, I will copy the locale file content into my own code, but hope your solution will help someone else :-)
