### ISSUE TITLE
[en-GB]: missing object `bytes` for language en-GB

### ISSUE THREAD

**Issue by seedy** [BenjaminVanRyseghem/numbro#558]
I got error with partial stacktrace below:
```
TypeError: Cannot read property 'binarySuffixes' of undefined
    at formatting.js:204
    at formatting.js:202
    at p (formatting.js:93)
    at Object.format (formatting.js:815)
    at e.value (numbro.js:40)
```

When looking a bit deeper, I dug this out: `languages[en-GB].bytes` is undefined

![Screenshot](https://user-images.githubusercontent.com/3367393/86904438-058db800-c111-11ea-8f7b-b89b91b1fba5.png)

**Comment by seedy** [comment]
:information_source: I import and register language en-GB from `numbro` package:
```
import numbroEN from 'numbro/languages/en-GB';
...
numbro.registerLanguage(numbroEN);
```

**Comment by BenjaminVanRyseghem** [comment]
Thanks! Indeed, it appears that those where implemented only in french (language used by the contributor) and en-US (language used by the tests).

I will patch it so that there are default values for every languages.

**Comment by BenjaminVanRyseghem** [comment]
@all-contributors please add @seedy  for bug
